services:
  - type: web
    name: ai-chat-backend
    runtime: node
    buildCommand: npm install
    startCommand: node dist/index.js
    envVars:
      - key: PORT
        value: 5000
      - key: FRONTEND_URL
        value: https://ai-chatt-nine.vercel.app
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
